version: "2"

services:
  rng:
    build: rng
    ports:
    - "8001:80"
    networks:
      - production

  hasher:
    build: hasher
    ports:
    - "8002:80"
    networks:
      - production
  webui:
    build: webui
    ports:
    - "8000:80"
    volumes:
    - "./webui/files/:/files/"
    networks:
      - production
  redis-master:
    build: redis
    ports:
    - "8006:6379"
    networks:
      production:
       ipv4_address: 12.5.0.50
  redis-replica-1:
    build: redis-replica
    ports:
    - "8004:9991"
    networks:
      production:
        ipv4_address: 12.5.0.20
  redis-replica-2:
    build: redis-replica
    ports:
    - "8005:9991" 
    networks:
      production:
        ipv4_address: 12.5.0.30
  sentinel-1:
    build: redis-sentinel
    networks:
      - production
  sentinel-2:
    build: redis-sentinel
    networks:
      - production
        
  sentinel-3:
    build: redis-sentinel
    networks:
      - production
 
  worker:
    build: worker
    networks:
      - production

  redis:
    image: haproxy:latest
    container_name: haproxy-container
    ports:
      - "6379:6379"  # Expose the Redis port through HAProxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg  # HAProxy config file
    networks:
      - production
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2

networks:

  production:
    driver: bridge
    ipam:
      config:
        - subnet: 12.5.0.0/24
          gateway: 12.5.0.1