version: "2"

services:
  rng:
    build: rng
    ports:
    - "8001:80"
    networks:
      - production

  hasher:
    build: hasher
    ports:
    - "8002:80"
    networks:
      - production
  webui:
    build: webui
    ports:
    - "8000:80"
    volumes:
    - "./webui/files/:/files/"
    networks:
      - production
  redis:
    build: redis
    ports:
    - "6379:6379"
    networks:
      production:
       ipv4_address: 12.5.0.50
      custom_net:
        ipv4_address: 10.5.0.50
      
      
  redis-replica-1:
    build: redis-replica
    ports:
    - "8004:9991"
    networks:
      custom_net:
        ipv4_address: 10.5.0.20
  redis-replica-2:
    build: redis-replica
    ports:
    - "8005:9991" 
    networks:
      custom_net:
        ipv4_address: 10.5.0.30
  sentinel-1:
    build: redis-sentinel
    networks:
      - custom_net
  sentinel-2:
    build: redis-sentinel
    networks:
      - custom_net
        
  sentinel-3:
    build: redis-sentinel
    networks:
      - custom_net
 
  worker:
    build: worker
    networks:
      - production
networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
          gateway: 10.5.0.1

  production:
    driver: bridge
    ipam:
      config:
        - subnet: 12.5.0.0/24
          gateway: 12.5.0.1